xf86bigfont: Fix -Werror=missing-prototypes build failure
../Xext/xf86bigfont.c: At top level:
../Xext/xf86bigfont.c:683:1: error: no previous prototype for
 ‘XFree86BigfontExtensionInit’ [-Werror=missing-prototypes]
  683 | XFree86BigfontExtensionInit(void)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~

Fixes: 33350ef8f ("include: move private definitions out of extinit.h")
Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
Part-of: <https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/2053>