Revert "os: move AbortServer() to os/utils.c"
This reverts commit 8e8bf639087f38dc6b24c4d55c1369acfe511a65.

It failed to build if xf86bigfont was enabled:
../os/utils.c: In function ‘AbortServer’:
../os/utils.c:1555:5: error: implicit declaration of function
 ‘XF86BigfontCleanup’ [-Wimplicit-function-declaration]
 1555 |     XF86BigfontCleanup();
      |     ^~~~~~~~~~~~~~~~~~

Part-of: <https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/2053>