Revert "Xext: shape: clean up Xinerama dispatch"
This reverts commit a57db845bbc67a7fe3f90390365420692b16b1ab.

It breaks when building with -Dxinerama=false:

../Xext/shape.c: In function ‘ProcShapeRectangles’:
../Xext/shape.c:318:12: error: too few arguments to function
 ‘ShapeRectangles’; expected 2, have 1
  318 |     return ShapeRectangles(client);
      |            ^~~~~~~~~~~~~~~

Part-of: <https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/2055>